# Generated by Django 4.1.7 on 2023-05-06 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsersDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField()),
                ('Gender', models.CharField(max_length=2)),
                ('birth_date', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
            ],
        ),
    ]
