# Generated by Django 4.1.7 on 2023-05-06 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersdetail',
            old_name='birth_date',
            new_name='email',
        ),
    ]
