# Generated by Django 4.1.7 on 2023-05-06 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_rename_birth_date_usersdetail_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersdetail',
            name='birth_date',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AlterField(
            model_name='usersdetail',
            name='email',
            field=models.CharField(default=0, max_length=155),
        ),
    ]
