# Generated by Django 4.1.7 on 2023-05-06 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_usersdetail_birth_date_alter_usersdetail_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersdetail',
            name='email',
            field=models.CharField(max_length=155),
        ),
    ]
