# Generated by Django 4.1.7 on 2023-05-07 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_alter_usersdetail_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersdetail',
            name='email',
            field=models.EmailField(max_length=225),
        ),
    ]
